services:
  - type: web
    name: playlist-analyzer
    env: node
    buildCommand: npm run prepare && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.x